language: node_js
node_js:
- '8.5'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_25a08a935a63_key -iv $encrypted_25a08a935a63_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --prod
after_success:
- ssh grid.best "sh ~/ci/run.sh"
addons:
  ssh_known_hosts: grid.best
