language: node_js
node_js:
- '8.5'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_25a08a935a63_key -iv $encrypted_25a08a935a63_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --prod
after_success:
  - ssh grid.best "sh ~/ci/run.sh" # 请替换成自己的登录IP和登录用户
addons:
  ssh_known_hosts: grid.best
